# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
# IP: The module: 'design_1_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
# IP: The module: 'design_1_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /tools/Xilinx/Vivado/2018.3/bin/Aula10_2/Aula10_2.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
